image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DQt5_DIR=C:\Qt\5.11.2\msvc2017_64\lib\cmake\Qt5 c:\projects\source -G "Visual Studio 15 2017 Win64"
  - cmd: cmake --build . --config "Debug"
