language: cpp
sudo: false

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
    - os: osx
      osx_image: xcode10

script:
  - cmake -DCMAKE_C_COMPILER=${C_FOR_BUILD} -DCMAKE_CXX_COMPILER=${CXX_FOR_BUILD} .
  - cmake --build . --config Debug