language: cpp
sudo: false

matrix:
  include:
    - os: windows
      env:
        - MATRIX_EVAL="CC=cc && CXX=cc"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - cmake --build . --config Debug