language: cpp
sudo: false

matrix:
  include:
    - os: windows
      env:
        - CMAKE_COMPILER=""
        - CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
    - os: linux
      dist: xenial
      before_install:
        - echo "Linux before_install"
        - add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - apt-get update -q
        - apt-get install gcc-8 -y
        - eval "${CMAKE_COMPILER}"
        - pip install --user conan
        - conan profile new default --detect
        - conan profile update settings.compiler.version=8 default
        - conan profile update settings.compiler.libcxx=libstdc++11 default
      env:
        - CMAKE_COMPILER="CC=gcc-8 && CXX=g++-8"
        - CMAKE_GENERATOR="Unix Makefiles"
    - os: osx
      osx_image: xcode10
      before_install:
        - echo "OSX before_install"
        - pip install --user conan
        - conan profile new default --detect
      env:
        - CMAKE_GENERATOR="Xcode"
        
before_script:
  - echo "before_script"
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - cmake -G"$CMAKE_GENERATOR" .
  - cmake --build . --config Debug