language: cpp

matrix:
  include:
    - os: windows
      env:
        - CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - pip install --user conan
        - conan profile new default --detect
    - os: linux
      dist: xenial
      env:
        - CMAKE_GENERATOR="Unix Makefiles"
      cache:
        timeout: 1000000
        directories:
          - /home/travis/.conan/data
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -q
        - sudo apt-get install gcc-8 g++-8 -y
        - CC=gcc-8 && CXX=g++-8
        - pip install --user conan
        - conan profile new default --detect
        - conan profile update settings.compiler.version=8 default
        - conan profile update settings.compiler.libcxx=libstdc++11 default
    - os: osx
      osx_image: xcode10
      env:
        - CMAKE_GENERATOR="Xcode"
      before_install:
        - pip install --user conan
        - PATH=$HOME/Library/Python/2.7/bin:$PATH
        - conan profile new default --detect

script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install .
  - cmake -G"$CMAKE_GENERATOR" .
  - cmake --build . --config Debug