language: cpp

matrix:
  include:
    - os: windows
      env:
        - CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
    - os: linux
      dist: xenial
      env:
        - CMAKE_GENERATOR="Unix Makefiles"
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -q
        - sudo apt-get install gcc-8 g++-8 -y
        - CC=gcc-8 && CXX=g++-8
        - pip install --user conan
        - conan profile new default --detect
        - conan profile update settings.compiler.version=8 default
        - conan profile update settings.compiler.libcxx=libstdc++11 default
    - os: osx
      osx_image: xcode10
      env:
        - CMAKE_GENERATOR="Xcode"
      before_install:
        - pip install --user conan
        - conan profile new default --detect
        
before_script:
  - echo "before_script"
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - cmake -G"$CMAKE_GENERATOR" .
  - cmake --build . --config Debug