dist: xenial
lauguage: cpp
sudo: false

os:
  - osx

compiler:
  - clang

addons:
  homebrew:
    packages:
      - cmake
      - cmake-data
    update: true

script:
  - cmake .
  - cmake --build . --config Debug