language: cpp
sudo: false

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      cache:
        timeout: 1000000000
        directories:
          - /home/travis/.conan

before_script:
  - eval "${MATRIX_EVAL}"
  - pip install --user conan
  - conan profile new default --detect
  - conan profile update settings.compiler.version=8 default
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - mkdir build && cd build && conan install ..

script:
  - cd build && cmake .. && cmake --build . --config Debug