lauguage: cpp
sudo: false

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc-8
    - os: osx
      osx_image: xcode10
      compiler: clang

script:
  - cmake .
  - cmake --build . --config Debug