language: cpp
sudo: false

matrix:
  include:
    - os: windows
      env:
        - CMAKE_COMPILER=""
        - CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CMAKE_COMPILER="CC=gcc-8 && CXX=g++-8"
        - CMAKE_GENERATOR="Unix Makefiles"
    - os: osx
      osx_image: xcode10
      env:
        - CMAKE_COMPILER="CC=clang && CXX=clang++"
        - CMAKE_GENERATOR="Xcode"

before_script:
  - eval "${CMAKE_COMPILER}"

script:
  - cmake -G$CMAKE_GENERATOR .
  - cmake --build . --config Debug