lauguage: cpp
sudo: false

osx_image: xcode10

matrix:
  include:
    - os: linux
      compiler: gcc-8
    - os: osx
      osx_image: xcode10
      compiler: clang

script:
  - cmake .
  - cmake --build . --config Debug