language: cpp
sudo: false

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

install:
  - pip install --user conan

#before_script:
#  - eval "${MATRIX_EVAL}"

#script:
#  - cmake .
#  - cmake --build . --config Debug